version: '3.8'

services:
  pg:
    image: bitnami/postgresql:latest
    container_name: intelectus-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Inicio@123
      - POSTGRES_DB=intelectus_db
    volumes:
      - postgres_data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d intelectus_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local 