"""Add process enums with correct values

Revision ID: 0200b0666e60
Revises: c8885d61a1f1
Create Date: 2025-07-20 23:00:23.290644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0200b0666e60'
down_revision: Union[str, Sequence[str], None] = 'c8885d61a1f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Criar enums para processos com valores corretos
    # Estes enums devem corresponder aos valores definidos no modelo Process
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE processtype AS ENUM ('BRAND', 'PATENT', 'DESIGN', 'SOFTWARE');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE processstatus AS ENUM ('PENDING', 'ACTIVE', 'GRANTED', 'DENIED', 'EXPIRED', 'ABANDONED');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE processsituation AS ENUM ('FILED', 'PUBLISHED', 'UNDER_EXAMINATION', 'OPPOSED', 'GRANTED', 'EXPIRED', 'LAPSED', 'RENEWED');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remover enums (cuidado: só se não houver dados dependentes)
    # op.execute("DROP TYPE IF EXISTS processtype CASCADE;")
    # op.execute("DROP TYPE IF EXISTS processstatus CASCADE;")
    # op.execute("DROP TYPE IF EXISTS processsituation CASCADE;")
    
    # ### end Alembic commands ###
