"""Altera status de Enum para String em process

Revision ID: 3d7e7f71d1be
Revises: 7ebef34b29ef
Create Date: 2025-07-23 00:13:41.546168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d7e7f71d1be'
down_revision: Union[str, Sequence[str], None] = '7ebef34b29ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('process', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACTIVE', 'GRANTED', 'DENIED', 'EXPIRED', 'ABANDONED', 'pendente', 'ativo', 'deferido', 'indeferido', 'expirado', 'abandonado', name='processstatus'),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('process', 'status',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('PENDING', 'ACTIVE', 'GRANTED', 'DENIED', 'EXPIRED', 'ABANDONED', 'pendente', 'ativo', 'deferido', 'indeferido', 'expirado', 'abandonado', name='processstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
