"""Altera status de Enum para String em process

Revision ID: 3d7e7f71d1be
Revises: 7ebef34b29ef
Create Date: 2025-07-23 00:13:41.546168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d7e7f71d1be'
down_revision: Union[str, Sequence[str], None] = '7ebef34b29ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Verificar se a coluna status existe e qual é o tipo atual
    connection = op.get_bind()
    result = connection.execute(sa.text("""
        SELECT data_type 
        FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'process' 
        AND column_name = 'status';
    """))
    
    row = result.fetchone()
    if row:
        current_type = row[0]
        
        # Se já é string (character varying), não precisa alterar
        if current_type in ('character varying', 'varchar', 'text'):
            # Verificar se precisa alterar o tamanho
            if current_type == 'character varying':
                # Verificar tamanho atual
                result = connection.execute(sa.text("""
                    SELECT character_maximum_length 
                    FROM information_schema.columns 
                    WHERE table_schema = 'public' 
                    AND table_name = 'process' 
                    AND column_name = 'status';
                """))
                size_row = result.fetchone()
                if size_row and size_row[0] and size_row[0] < 100:
                    # Aumentar tamanho se necessário
                    op.alter_column('process', 'status',
                                   existing_type=sa.String(length=size_row[0]),
                                   type_=sa.String(length=100),
                                   existing_nullable=False)
            return  # Já é string, não precisa alterar
        
        # Se é enum, alterar para string
        if current_type == 'USER-DEFINED':
            # Verificar se é realmente o enum processstatus
            result = connection.execute(sa.text("""
                SELECT udt_name 
                FROM information_schema.columns 
                WHERE table_schema = 'public' 
                AND table_name = 'process' 
                AND column_name = 'status';
            """))
            udt_row = result.fetchone()
            if udt_row and udt_row[0] == 'processstatus':
                # Alterar de enum para string
                op.alter_column('process', 'status',
                               existing_type=postgresql.ENUM('PENDING', 'ACTIVE', 'GRANTED', 'DENIED', 'EXPIRED', 'ABANDONED', 'pendente', 'ativo', 'deferido', 'indeferido', 'expirado', 'abandonado', name='processstatus'),
                               type_=sa.String(length=100),
                               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('process', 'status',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('PENDING', 'ACTIVE', 'GRANTED', 'DENIED', 'EXPIRED', 'ABANDONED', 'pendente', 'ativo', 'deferido', 'indeferido', 'expirado', 'abandonado', name='processstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
